### ISSUE TITLE
Need contributing guidelines + CoC

### ISSUE THREAD

**Issue by rmarkello** [rmarkello/pyls#11]

**Comment by emdupre** [comment]
Opened #16 to address this. One question it brings up&mdash; how do you want to acknowledge contributors ?

**Comment by rmarkello** [comment]
I'm happy with the [all-contributors](https://github.com/kentcdodds/all-contributors) method, but am open to suggestions!

**Comment by emdupre** [comment]
I think for now that might be a little much (since there are just two of us !). Once literally anyone else is involved, I think we can reevaluate. In https://github.com/rmarkello/pyls/pull/17/commits/2c4dce77fd05b370807535d95032209a96a98b5c, I just add a link back to the "Contributors" view in GitHub. WDYT ?

**Comment by rmarkello** [comment]
Looks great! I'll go ahead and merge.

**Comment by rmarkello** [comment]
Closed with #17.
