### ISSUE TITLE
Dot product of scores is not equal to singular values

### ISSUE THREAD

**Issue by seralouk** [rmarkello/pyls#56]
I am running the following:
```
from pyls.examples import load_dataset
from pyls.compute import xcorr
from pyls.compute import svd
from scipy.stats import zscore
import numpy as np

# Way 1
data = load_dataset('linnerud')
R = xcorr(data.X, data.Y, norm=False, covariance=False) # internal z-scoring and division by N-1 is done
U, S, V = svd(R) # SVD using sklearn internally 

# Way 2
myX = zscore(data.X,ddof=1)
myY = zscore(data.Y,ddof=1)
myR=np.dot(myY.T,myX) / (len(myX)-1)
myU, myS, myVh = np.linalg.svd(myR) # SVD from numpy
myS = np.diag(myS)

#Point 1
np.allclose(myR,R) # passes, same Cross-correlation matrices
np.allclose(U,myU) # does not pass, different orthogonal bases

# Point 2
# singular value is equal to covariance of the correponding vectors of scores
myXV = np.dot(myX, myVh.T)
myYU = np.dot(myY, myU)
np.allclose(np.dot(myXV[:,0], myYU[:,0]) / (len(myXV)-1) , myS[0][0]) # True, correct

data.X = zscore(data.X, 0, ddof=1)
data.Y = zscore(data.Y, 0, ddof=1)
XV = np.dot(data.X, V)
YU = np.dot(data.Y, U)
np.allclose(np.dot(XV[:,0], YU[:,0]) / (len(XV)-1) , S[0][0]) # False !
```

Reference: doi:10.1016/j.neuroimage.2010.07.034, equation (9)

Point 1: Why `np.allclose(U,myU)` does not pass?
Point 2: Why `np.allclose(np.dot(XV[:,0], YU[:,0]) / (len(XV)-1) , S[0][0])` return False?

EDIT

Additonally, in this tutorial (https://github.com/rmarkello/pyls/blob/master/docs/user_guide/behavioral.rst)

`XU = np.dot(data.X, U)` should be `XV = np.dot(data.X, V)` and `YV = np.dot(data.Y, V)` -> `YU = np.dot(data.Y, U)`

**Comment by rmarkello** [comment]
Hi @seralouk, and welcome to `pyls`! Thanks for including so much detail in your question !

I totally understand your confusion here, and the reason for this is completely historical (i.e., because `pyls` originated as a translation of the [original Matlab `Pls` toolbox](https://www.rotman-baycrest.on.ca/index.php?section=84)). First, let me try and show you what would "work" for the questions you posed (and then I'll try and get into the "why"):

1. `np.allclose(U, myVh.T)` will evaluate to `True`
2. For the same reason, `np.allclose(np.dot(np.dot(data.X, U)[:, 0], np.dot(data.Y, V)[:, 0]) / (len(data.X) - 1), S[0][0])` will evaluate to `True`

The reason for this is, as I mentioned, historical. In the original implementation of the Matlab `Pls` toolbox the `X` matrix traditionally represented brain imaging data and was therefore much, much larger in dimensionality than the `Y` (which represented "behavioral" data like clinical scores or similar). However, the authors also wanted `X` to be associated with the left singular values (i.e., `U`), so they conduct the SVD on the transposed cross-covariance matrix.  You can see we replicate that behavior in the `pyls.compute.svd` function:

https://github.com/rmarkello/pyls/blob/d8a19d564cc5804249527b68c937df3a5fd8c7cc/pyls/compute.py#L43-L50

For this same reason, the calculation of the `XU` and `YV` scores in the referenced tutorial is accurate (though, admittedly, confusing). 

In my mind, there are two options moving forward:

1. Modify the `pyls` code so that it mirrors what would be expected by convention (i.e., `X` corresponds to `V` and `Y` corresponds to `U`), or
2. Update the documentation (and tutorials) to be very clear about this historical precedent and our rationale for keeping it as-is.

I would personally prefer to do option 2; however, since you raised the issue I would be open to your thoughts and feedback here!

(Hopefully this is clear, but let me know if you have any lingering questions!)

**Comment by seralouk** [comment]
Hi @rmarkello. Crystal clear answer. Thanks. I would expect brain saliences to be `V` but I missed the transposition before the SVD. Now, it makes sense.

I agree with option 2 and potentially you could state explicitly in the `README` that `U` is actually the brain saliences to avoid future confusion.  Additionally, I am not very familiar with the intial Matlab implementation so I wanted to ask you whether the normalization term for the `R` was alos used there (`(len(XV)-1)`). Nothing changes in reality, but most recent papers omit it and state that if `X`and `Y` are column-wise zscored then the `R=Y'X` is the cross-covariance == cross-correlation matrix.

**Comment by rmarkello** [comment]
Awesome! I'll try and work on updating the docs soon (I haven't had much time for this project in recent weeks, unfortunately ☹️).

Re your question about normalization: yes, the original implementation does normalize by `n_samples - 1`. As you noted, it doesn't change the resulting singular vectors (and simply scales the singular values), but I think that being able to interpret the `R` matrix as a set of correlations can be quite nice!
